CREATE DATABASE IF NOT EXISTS taskdb;

CREATE TABLE Tasks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    cost DECIMAL(10, 2) NOT NULL,
    endDate DATE NOT NULL,
    `order` INT
);