CREATE DATABASE IF NOT EXISTS taskdb;

CREATE TABLE tasks (
    id CHAR(24) PRIMARY KEY DEFAULT (SUBSTRING(UUID(), 1, 24)),
    name VARCHAR(255) NOT NULL UNIQUE,
    cost DECIMAL(11, 2) NOT NULL,
    endDate DATE NOT NULL,
    `order` INT,
    UNIQUE (id, name)
);