CREATE DATABASE IF NOT EXISTS taskdb;

CREATE TABLE tasks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    cost VARCHAR(255) NOT NULL,
    endDate DATE,
    ordem INT NOT NULL UNIQUE
);